// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    appId: '1:396185360207:web:138193c58f5d61d1a6973a',
    messagingSenderId: '396185360207',
    projectId: 'bucksbuddy-a19e7',
    authDomain: 'bucksbuddy-a19e7.firebaseapp.com',
    storageBucket: 'bucksbuddy-a19e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    appId: '1:396185360207:android:c8739aca45c9186fa6973a',
    messagingSenderId: '396185360207',
    projectId: 'bucksbuddy-a19e7',
    storageBucket: 'bucksbuddy-a19e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    appId: '1:396185360207:ios:c75eb8a7444f87dfa6973a',
    messagingSenderId: '396185360207',
    projectId: 'bucksbuddy-a19e7',
    storageBucket: 'bucksbuddy-a19e7.appspot.com',
    androidClientId: '396185360207-eh7ofkqaksq25efocak8ikilvcmiubt5.apps.googleusercontent.com',
    iosClientId: '396185360207-k198ajovrspo8j5e7leen3vq3mcdv3dg.apps.googleusercontent.com',
    iosBundleId: 'com.example.bucksBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    appId: '1:396185360207:web:c0a1e04669b5ec2ea6973a',
    messagingSenderId: '396185360207',
    projectId: 'bucksbuddy-a19e7',
    authDomain: 'bucksbuddy-a19e7.firebaseapp.com',
    storageBucket: 'bucksbuddy-a19e7.appspot.com',
  );

}